environment:
  SpotifyClientId:
    secure: Xpy+h+EsCwaT/dEtuwQUVJka2iZMCvTpU6xhzu63Ekyz0QJqjP8Invf+D/kn7ubt
  SpotifyClientSecret:
    secure: XxzzP7R4nJlRLcF0q81e8f6hKO5LhP+SVIJBDaW9fCvB8EaugS7IxHxX75KGXRxE
  Settings:
    secure: 806CJt0lG8igqzGr/g7n6Q==
  SpotiqueueUserName:
    secure: mI1F7gQznjKQMO2btnoLYg==
  SpotiqueuePlaylistId:
    secure: VjF44977tf2j4+QdpVJRiFlXClPuHQEOU6LnXIrwaAU=
before_build:
  - nuget restore
build: 
  publish_wap: true
test:
  categories:
    only: 
      - Unit
deploy:
  - provider: WebDeploy
    server: ec2-52-38-44-244.us-west-2.compute.amazonaws.com
    website: XeroNet/Spotiqueue.UI/
    username: Administrator
    password: HM.RUbg(D2&